run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    # these are enabled by default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # cherry picked from https://golangci-lint.run/usage/linters/
    # - ginkgolinter # to be enabled once #158 is merged
    - bodyclose
    - exportloopref
    - gocheckcompilerdirectives
    - gofmt
    - goimports
    - importas
    - loggercheck
    - makezero
    - nilerr
    - prealloc
    - reassign
    - tenv
    - unconvert
    - wastedassign
    - unparam
    - gofumpt
    - nosprintfhostport
    - musttag
    - exhaustive
    - nilnil

issues:
  exclude-rules:
    - path: cloud/linode/fake_linode_test.go
      text: 'SA1019: (.+).(NodeBalancersPagedResponse|NodeBalancerConfigsPagedResponse|NodeBalancerNodesPagedResponse|FirewallDevicesPagedResponse) is deprecated: (NodeBalancersPagedResponse|NodeBalancerConfigsPagedResponse|NodeBalancerNodesPagedResponse|FirewallDevicesPagedResponse) exists for historical compatibility and should not be used.'
