run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    # these are enabled by default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # cherry picked from https://golangci-lint.run/usage/linters/
    # - ginkgolinter # to be enabled once #158 is merged
    - bodyclose
    - copyloopvar
    - gocheckcompilerdirectives
    - gofmt
    - goimports
    - importas
    - loggercheck
    - makezero
    - nilerr
    - prealloc
    - reassign
    - tenv
    - unconvert
    - wastedassign
    - unparam
    - gofumpt
    - nosprintfhostport
    - musttag
    - exhaustive
    - nilnil
