run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    # these are enabled by default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # cherry picked from https://golangci-lint.run/usage/linters/
    - ginkgolinter
    - bodyclose
    - exportloopref
    - gocheckcompilerdirectives
    - gofmt
    - goimports
    - importas
    - loggercheck
    - makezero
    - nilerr
    - prealloc
    - reassign
    - tenv
    - unconvert
    - wastedassign
    # enable once we're ready for a more involved refactor:
    # - unparam # lots of unused function arguments
    # - gofumpt # can be autofixed, it'd just produce a large diff
    # - nosprintfhostport # nit
    # - musttag # needs testing
    # - exhaustive # needs careful refactors to satisfy
    # - nilnil # needs testing