apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ccm-linode
  labels:
    app: ccm-linode
  namespace: {{ required ".Values.namespace required" .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: ccm-linode
  template:
    metadata:
      labels:
        app: ccm-linode
    spec:
      serviceAccountName: ccm-linode
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      hostNetwork: true
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: ccm-linode
          args:
            - --leader-elect-resource-lock=endpoints
            - --v=3
            - --port=0
            - --secure-port=10253
            {{- if .Values.linodegoDebug }}
            - --linodego-debug={{ .Values.linodegoDebug }}
            {{- end }}
            {{- if .Values.routeController }}
            - --enable-route-controller=true
            - --vpc-name={{ .Values.routeController.vpcName }}
            - --linode-node-private-subnet={{ .Values.routeController.linodeNodePrivateSubnet }}
            {{- if .Values.routeController.configureCloudRoutes }}
            - --configure-cloud-routes={{ .Values.routeController.configureCloudRoutes }}
            {{- end }}
            {{- if .Values.routeController.routeReconciliationPeriod }}
            - --route-reconciliation-period={{ .Values.routeController.routeReconciliationPeriod }}
            {{- end }}
            {{- end }}
          volumeMounts:
            - mountPath: /etc/kubernetes
              name: k8s
          env:
            - name: LINODE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.secretRef }}{{ .Values.secretRef.name | default "ccm-linode" }}{{ else }}"ccm-linode"{{ end }}
                  key: {{ if .Values.secretRef }}{{ .Values.secretRef.apiTokenRef | default "apiToken" }}{{ else }}"apiToken"{{ end }}
            - name: LINODE_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.secretRef }}{{ .Values.secretRef.name | default "ccm-linode" }}{{ else }}"ccm-linode"{{ end }}
                  key: {{ if .Values.secretRef }}{{ .Values.secretRef.regionRef | default "region" }}{{ else }}"region"{{ end }}
            {{if .Values.env}}
            {{- toYaml .Values.env | nindent 12 }}
            {{end}}
      volumes:
        - name: k8s
          hostPath:
            path: /etc/kubernetes