apiVersion: v1
kind: ServiceAccount
metadata:
  name: ccm-linode
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: system:ccm-linode
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: ccm-linode
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccm-linode
  labels:
    app: ccm-linode
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccm-linode
  template:
    metadata:
      labels:
        app: ccm-linode
    spec:
      serviceAccountName: ccm-linode
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
        effect: NoSchedule
      containers:
        - image: appscode/ccm-linode:external
          imagePullPolicy: Always
          name: ccm-linode
          args:
          - up
          - --cloud-config=/etc/kubernetes/cloud-config
          - --cloud-provider=linode
          - --v=3
          volumeMounts:
          - mountPath: /etc/kubernetes
            name: k8s
          ports:
            - containerPort: 9844
              name: web
              protocol: TCP
      volumes:
      - name: k8s
        hostPath:
          path: /etc/kubernetes
