---
kind: Service
apiVersion: v1
metadata:
  name: http-lb
  namespace: kube-system
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-default-protocol: "http"
    service.beta.kubernetes.io/linode-loadbalancer-firewall-acl: |
      {
        "allowList": {
          "ipv4": ["8.8.8.8/32"],
          "ipv6": ["dead:beef::/64"]
        }
      }
spec:
  type: LoadBalancer
  selector:
    app: nginx-http-example
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-http-deployment
  namespace: kube-system    
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-http-example
  template:
    metadata:
      labels:
        app: nginx-http-example
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          protocol: TCP
